.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FSUM" "8" "December 2015" "" ""
.
.SH "NAME"
\fBfsum\fR \- A Scalable Parallel Checksum Tool
.
.SH "SYNOPSIS"
.
.nf

fsum file1 file2 \.\.\.
fsum dir

mpirun \-np 8 fsum \.\.\.
.
.fi
.
.SH "DESCRIPTION"
\fBfsum\fR is a program designed to do large scale data checksumming\. Compare to conventional checksumming utilities such as \fBmd5sum\fR, there are two major differences: (1) It is parallel; (2) It is dataset\-based instead of file\-based\. \fBfsum\fR supports the following options:
.
.TP
\fB\-\-output filename\fR
Rename signature file\. By default, fsum generate signature file using current time stamp\.
.
.TP
\fB\-\-chunksize sz\fR
\fBfsum\fR will break up large files into pieces to increase parallelism\. By default, \fBfsum\fR adaptively sets the chunk size based on the overall size of the workload\. Use this option to specify a particular chunk size in KB, MB\. For example, \fB\-\-chunksize 128MB\fR\.
.
.TP
\fB\-\-reduce\-interval\fR
Controls progress report frequency\. The default is 10 seconds\.
.
.TP
\fB\-\-\-\-export\-block\-signatures\fR
Control if the signature file contains checksums of each data block\. By default, only the aggregated checksum is saved\.
.
.SH "PERFORMANCE/RESOURCE CONSIDERATIONS"
The final step of aggregating and sorting block checksums are not parallelized\. The reduction is performed on a single node eventually\. This step will require large memory footprint as the number of files increases\.
.
.SH "AUTHOR"
Feiyi Wang (fwang2@ornl\.gov)
