.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FPROF" "8" "June 2018" "" ""
.
.SH "NAME"
\fBfprof\fR \- File System Profiler
.
.SH "SYNOPSIS"
.
.nf

fprof target_directory

mpirun \-np 8 fprof \|\.\|\.\|\.
.
.fi
.
.SH "DESCRIPTION"
\fBfprof\fR is a lightweight profiler designed to provide a set of useful statistical characterization of the target file system at extreme scale\. A sample report on ORNL Atlas file system is as the following:
.
.IP "" 4
.
.nf

Fileset histograms:

        <  4\.00 KiB       19888046           17\.08%    ∎∎∎∎∎∎∎∎
        <  8\.00 KiB       5708765             4\.90%    ∎∎
        <  16\.00 KiB      4376361             3\.76%    ∎
        <  32\.00 KiB      5366888             4\.61%    ∎∎
        <  64\.00 KiB      7061464             6\.07%    ∎∎∎
        <  256\.00 KiB     13388304           11\.50%    ∎∎∎∎∎
        <  512\.00 KiB     8406809             7\.22%    ∎∎∎
        <  1\.00 MiB       3652496             3\.14%    ∎
        <  4\.00 MiB       13817394           11\.87%    ∎∎∎∎∎
        <  16\.00 MiB      13088330           11\.24%    ∎∎∎∎∎
        <  512\.00 MiB     18992735           16\.32%    ∎∎∎∎∎∎∎∎
        <  1\.00 GiB       1918471             1\.65%
        <  100\.00 GiB     740765              0\.64%
        <  256\.00 GiB     2779                0\.00%
        <  512\.00 GiB     630                 0\.00%
        <  1\.00 TiB       699                 0\.00%
        >  1\.00 TiB       458                 0\.00%

Fprof epilogue:

        Directory count:         35,945,074
        Sym Links count:         1,050,485
        File count:              116,411,394
        Skipped count:           364
        Total file size:         8160\.08 TiB
        Avg file size:           73\.50 MiB
        Max files within dir:    1,003,319
.
.fi
.
.IP "" 0
.
.P
\fBfprof\fR supports many other options:
.
.P
\fB\-\-cpr\fR
.
.br
Estimate compression saving
.
.P
\fB\-\-cpr\-per\-file\fR
.
.br
Print compression saving for each file
.
.P
\fB\-\-dii\fR
.
.br
Enable data\-in\-inode (dii)
.
.P
\fB\-\-dirprof\fR
.
.br
Enable directory count profiling
.
.P
\fB\-\-dirbins <INT[ INT INT\|\.\|\.\|\.]>\fR
.
.br
Directory bins for histogram, list each bin in order e\.g\. \-\-dirbins 100 1000 100000 \|\.\|\.\|\.
.
.P
\fB\-\-exclude <FILE>\fR
.
.br
A file with exclusion list
.
.P
\fB\-\-gpfs\-block\-alloc\fR
.
.br
GPFS block usage analysis\. This is to aid the transition from Lustre\-based file system to GPFS\-based file system and reports the GPFS block usage characterization\.
.
.P
\fB\-h, \-\-help\fR
.
.br
Print out the help menu
.
.P
\fB\-i, \-\-interval <INTERVAL>\fR
.
.br
Interval
.
.P
\fB\-inodesz <INODESZ>\fR
.
.br
Inode size, default 4k
.
.P
\fB\-\-item <ITEM>\fR
.
.br
Number of items stored in memory, default: 3000000
.
.P
\fB\-\-loglevel <LOGLEVEL>\fR
.
.br
Log Level
.
.P
\fB\-\-lustre\-stripe\fR
.
.br
Lustre stripe analysis
.
.P
\fB\-\-perfile\fR
.
.br
Save perfile file size for more analysis
.
.P
\fB\-\-perprocess\fR
.
.br
Enable per\-process progress report
.
.P
\fB\-\-profdev\fR
.
.br
Enable dev profiling
.
.P
\fB\-\-progress\fR
.
.br
Enable periodoic progress report
.
.P
\fB\-\-sparse\fR
.
.br
Print out detected spare files
.
.P
\fB\-\-stripe\-output\fR
.
.br
Stripe output file
.
.P
\fB\-\-stripe\-threshold <N>\fR
.
.br
Lustre stripe file size threshold above which to analyze, default is 4GB
.
.P
\fB\-\-syslog\fR
.
.br
Enable syslog report
.
.P
\fB\-\-topn\-dirs <TOPN_DIRS>\fR
.
.br
Print out the top N largest directories
.
.P
\fB\-\-topn\-files <TOPN_FILES>\fR
.
.br
Print out the top N largest files
.
.P
\fB\-v\fR
.
.br
Verbose mode
.
.P
\fB\-\-version\fR
.
.br
Show program version number and exit
.
.P
An sample output of \fB\-\-gpfs\-block\-alloc\fR is as the following, against a dataset with mostly small files\. The report shows that if GPFS blocksize is 8M, then the 1GB dataset will inflate 10x to 10\.39GB, with a poor space efficiency of 10%\. \fBHowever\fR, this trend should not generalize to other file systems\. We observe that for file system with many large files, this space inefficiency issue can be largely neglected\.
.
.IP "" 4
.
.nf

GPFS Block Alloc Report:

        Subblocks: [162887  90033  64419  45701  42551]

        Blocksize: 256k     Estimated Space: 1\.24 GiB               Efficiency:    86%
        Blocksize: 512k     Estimated Space: 1\.37 GiB               Efficiency:    78%
        Blocksize: b1m      Estimated Space: 1\.97 GiB               Efficiency:    55%
        Blocksize: b4m      Estimated Space: 5\.58 GiB               Efficiency:    19%
        Blocksize: b8m      Estimated Space: 10\.39 GiB              Efficiency:    10%
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Feiyi Wang (fwang2@ornl\.gov), Cameron Harr (charr@llnl\.gov)
